# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20170307_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='url',
            field=models.CharField(default='null', max_length=1024),
            preserve_default=False,
        ),
    ]
